### PR TITLE
add hebrew translation

### PR DESCRIPTION
**Pull request by DeDuplicate**

### CODE REVIEW

**Comment by potts99** [comment]
haha quality appreciate man, will take a deeper look as my hebrew is a little no existant

**Comment by potts99** [comment]
Could you update to the following code structure so i can give you the merge credits?

**Comment by DeDuplicate** [comment]
i fixed the files can you check now?

**Comment by DeDuplicate** [comment]
> Could you update to the following code structure so i can give you the merge credits?
i don't understand what you mean?

**Comment by DeDuplicate** [comment]
@potts99  can you please help me to solve this?

**Review by potts99 — APPROVED** [review]

**Pull request merged**
